[build]
builder = "NIXPACKS"
watch = ["backend/**"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["cd backend && npm install"]

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
